### ISSUE TITLE
论坛跑了一天下来会停止

### ISSUE THREAD

**Issue by hzhou81** [zhangjianhao/BBS#9]
我看了页面上index.jsp上的报错是mysql超时，我在数据库连接字符串里使用了autoConnect=true还是用了一段时间以后会报错。

**Comment by hzhou81** [comment]
不知道是我mysql的设置问题，还是程序的问题。

**Comment by zhangjianhao** [comment]
@hzhou81 这个项目是以前做的一个javaee课设，有很多不完善的地方，数据库的连接确实存在你说的那个问题，原因估计是hibernate没有管理好数据库连接，导致连接数过多。
